# Generated by Django 3.0.4 on 2020-08-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user',
        ),
    ]
