# Generated by Django 3.0.4 on 2020-08-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hackapp', '0002_auto_20200827_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
