# Generated by Django 3.1 on 2020-08-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackapp', '0004_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='canditates',
            fields=[
                ('date', models.DateTimeField()),
                ('canditate_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=None, null=True)),
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('experience', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('domain', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('current_ctc', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('expected_ctc', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('notice_period', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='role_table',
            fields=[
                ('role_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rounds', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rounds_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_round', models.IntegerField(blank=True, default=None)),
                ('status_application', models.CharField(blank=True, default=None, max_length=20)),
                ('feedback', models.CharField(blank=True, default=None, max_length=20)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hackapp.canditates')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hackapp.role_table')),
            ],
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
